# Generated by Django 4.2.3 on 2023-08-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_blog_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
